name: georoute
description: Route geospatial data to various backends and protocols
homepage: https://github.com/synw/georoute
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  meta: ^1.1.8
  geopoint: ^0.7.1
  dio: ^3.0.9

dev_dependencies:
  test: ^1.6.5
  test_coverage: ^0.4.1
